
pgmEcho:     pgmEcho.c pgmRead.c pgmWrite.c pgmValidation.c pgmValidationWrite.c           pgmDef.h pgmRead.h pgmWrite.h pgmValidation.h pgmValidationWrite.h pgmComp.h
							            
	gcc  -g -std=c99 -fmax-errors=1 -Wall -Werror						     -o pgmEcho    pgmEcho.c pgmRead.c pgmWrite.c pgmValidation.c pgmValidationWrite.c

pgmCompare:  pgmCompare.c pgmRead.c pgmValidation.c pgmComp.c           	  pgmDef.h pgmRead.h pgmValidation.h pgmComp.h
	gcc  -g -std=c99 -fmax-errors=1 -Wall -Werror   		          -o pgmCompare    pgmCompare.c pgmRead.c pgmValidation.c pgmComp.c

pgma2b:	pgma2b.c pgmRead.c pgmWrite.c pgmValidation.c pgmValidationWrite.c        pgma2b.h pgmDef.h pgmRead.h pgmEchoStructs.h pgmWrite.h  pgmValidation.h pgmValidationWrite.h
	gcc -g -std=c99 -fmax-errors=1 -Wall -Werror				  -o pgma2b	pgma2b.c  pgmRead.c pgmWrite.c pgmValidation.c pgmValidationWrite.c

pgmb2a: pgmb2a.c pgmRead.c pgmWrite.c pgmValidation.c pgmValidationWrite.c	  pgmb2a.h pgmDef.h pgmRead.h pgmEchoStructs.h pgmWrite.h  pgmValidation.h pgmValidationWrite.h
	gcc -g -std=c99 -fmax-errors=1 -Wall -Werror				  -o pgmb2a     pgmb2a.c  pgmRead.c pgmWrite.c pgmValidation.c pgmValidationWrite.c

pgmReduce: pgmReduce.c pgmRead.c pgmWrite.c pgmValidation.c pgmValidationWrite.c        pgmReduce.h pgmDef.h pgmRead.h pgmEchoStructs.h pgmWrite.h  pgmValidation.h pgmValidationWrite.h
	gcc -g -std=c99 -fmax-errors=1 -Wall -Werror                               -o pgmReduce     pgmReduce.c  pgmRead.c pgmWrite.c pgmValidation.c pgmValidationWrite.c
	

