#define EXIT_NO_ERRORS 0
#define EXIT_WRONG_ARG_COUNT 1
#define EXIT_BAD_INPUT_FILE 2
#define EXIT_BAD_OUTPUT_FILE 3
#define EXIT_NOT_LOGICALLY_EQUIVALENT 3
#define BAD_FILE_NAME 3
#define BAD_COMMENT_LINE 4
#define BAD_MAGIC_NUMBER 3
#define BAD_DIMENSIONS 5
#define BAD_DATA 8
#define IMAGE_MEMORY_FAIL 7
#define NBYTESWRITTENFAIL 9

#define MAGIC_NUMBER_RAW_PGM 0x3550
#define MAGIC_NUMBER_ASCII_PGM 0x3250
#define MIN_IMAGE_DIMENSION 1
#define MAX_IMAGE_DIMENSION 65536
#define MAX_COMMENT_LINE_LENGTH 128
long nImageBytes;
